//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morichbati_Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Events = new HashSet<Event>();
        }
    
        public string ServiceID { get; set; }
        public string Venue { get; set; }
        public string Theme { get; set; }
        public string Photographar { get; set; }
        public string ShoppingGuide { get; set; }
        public string JwelleryGuide { get; set; }
        public string InvitationCard { get; set; }
        public string SoundSystem { get; set; }
        public string Entertainment { get; set; }
        public string DessertDecoration { get; set; }
        public string FlowerDecoration { get; set; }
        public string Palki_Horse { get; set; }
        public string Caterer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
